### ISSUE TITLE
How get access token apple

### ISSUE THREAD

**Issue by lavanphat** [abouroubi/passport-apple-verify-token#2]
I used package but i don't know get access token apple

**Comment by abouroubi** [comment]
Hi @lavanphat, the package is used to validate the token not to retrieve it.
The token is retrieved from the client side, and then sent to the backend for validation only.

**Comment by lavanphat** [comment]
Is there any tools for me to get the access token of apple like google
[access token google](https://developers.google.com/oauthplayground/)

**Comment by abouroubi** [comment]
Unfortunately , there is no such thing for Sign In With Apple, at least, not one that I'm aware of.
