### ISSUE TITLE
How to Implement the call back

### ISSUE THREAD

**Issue by fd98279** [abouroubi/passport-apple-verify-token#3]
Hello,

Thanks for this package. Could you give more details on how to implement the call back? The call back should return the email ID so when I create the user I can map the email ID to the local system user details.

Per README.md:
`
    function(token, appleId, done) {
      User.findOrCreate(..., function (err, user) {
        done(err, user);
      });
    }
`

Usually other token strategies provide the user profile like this:
For Facebook-token
`
		function (req, accessToken, refreshToken, profile, done) {
			// Set the provider data and include tokens
			var providerData = profile._json;
			providerData.accessToken = accessToken;
			providerData.refreshToken = refreshToken;

			// Create the user OAuth profile. 
			var providerUserProfile = {
				facebookId: profile.id,
				firstName: profile.name[1],
				lastName: profile.name[0],
				middleName: profile.name[2],
				displayName: profile.displayName,
				gender: profile.gender,
				profileUrl: profile.profileUrl,
				email: profile.emails[0].value,
				photoUrl: profile.photo,
				username: profile.displayName,
				provider: 'facebook',
				providerIdentifierField: 'id',
				providerData: providerData
			};

			// Save the user OAuth profile
			users.saveOAuthUserProfile(req, providerUserProfile, done);
		}
`

Per this document: https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/configuring_your_webpage_for_sign_in_with_apple

Apple returns this data
`
{
     "authorization": {
       "state": "[STATE]",
       "code": "[CODE]",
       "id_token": "[ID_TOKEN]"
     },
     "user": {
       "email": "[EMAIL]",
       "name": {
         "firstName": "[FIRST_NAME]",
         "lastName": "[LAST_NAME]"
       }
     }
}
`

**Comment by fd98279** [comment]
appleId is the email ID so we can just use appleID as reference in the local system right, Apple does not send user name after initial sign in so you do not return user name to the call back?

**Comment by abouroubi** [comment]
Hello,
Yes SignIn with Apple do not have the same behavior as Facebook, you just have the email in the token received.
