### ISSUE TITLE
Format of clientId

### ISSUE THREAD

**Issue by MakakWasTaken** [abouroubi/passport-apple-verify-token#5]
I have now tried to get this working for the past two days, but I keep running into new issues. My problem currently is that jose claims that my token has an invalid "aud" claim (Or audience).

I was wondering what the format of the clientId is. Currently, I have <Team ID>.<Application Identifier>

So for example 

AA11AA11AA.com.company.example

Is this not what it is supposed to look like? Or is the error 
```JWTClaimInvalid: unexpected "aud" claim value```
Coming from something else?

**Comment by abouroubi** [comment]
Hi @MakakWasTaken 

For me I just use the Bundle Identifier of my iOS app

**Comment by MakakWasTaken** [comment]
That did not work for me, but I figured out why it was not working. I needed to use the Service ID from the Sign in with Apple service.
